name: gogogo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  firebase_auth: ^5.1.2
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0
  http: 1.2.1
  cupertino_icons: ^1.0.2
  
  form_field_validator: ^1.1.0
  numberpicker: ^2.0.2
  
  flutter_widget_from_html_core: ^0.15.1
  animations: ^2.0.11
  url_launcher: ^6.3.0
  input_quantity: ^2.3.4
  firebase_storage: ^12.1.1
  firebase_database: ^11.0.3
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/Illustration/
  # fonts:
  #   - asset: assets/fonts/Poppins-SemiBold.ttf 
  #     weight: 600
  #   - asset: Assets/fonts/Poppins-Medium.ttf 
  #     weight: 500
  #   - asset: Assets/fonts/Poppins-Bold.ttf 
  #     weight: 700
  #   - asset: Assets/fonts/Poppins-Regular.ttf 
  #     weight: 400
